apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "node-labeler.labels" . | nindent 4 }}
  name: {{ include "node-labeler.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - 'nodes'
  verbs:
  - get
  - list
  - patch