---
apiVersion: v1
kind: ConfigMap
metadata:
 name: worker-labels-yaml
 labels:
   {{- include "node-labeler.labels" . | nindent 4 }}
data:
  worker-labels.yaml: |
    metadata:
      labels:
        node-role.kubernetes.io/worker: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: spot-labels-yaml
 labels:
   {{- include "node-labeler.labels" . | nindent 4 }}
data:
  spot-labels.yaml: |
    metadata:
      labels:
        node-role.kubernetes.io/spot-worker: ""