---
apiVersion: v1
kind: ConfigMap
metadata:
 name: worker-labels-conf
 labels:
   {{- include "node-labeler.labels" . | nindent 4 }}
data:
  worker-labels.conf: |
    {
      "metadata": {
        "labels": {
          "node-role.kubernetes.io/worker": ""
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: spot-labels-conf
 labels:
   {{- include "node-labeler.labels" . | nindent 4 }}
data:
  spot-labels.conf: |
    {
      "metadata": {
        "labels": {
          "node-role.kubernetes.io/spot-worker": ""
        }
      }
    }