---
apiVersion: v1
kind: ConfigMap
metadata:
 name: labels-conf
 labels:
   {{- include "node-labeler.labels" . | nindent 4 }}
data:
  labels.conf: |
     worker = {
       "metadata": {
         "labels": {
           "node-role.kubernetes.io/worker": ""
         }
       }
     }

     spot = {
       "metadata": {
         "labels": {
           "node-role.kubernetes.io/spot-worker": ""
         }
       }
     }