apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-labeler.fullname" . }}
  labels:
    {{- include "node-labeler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-labeler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node-labeler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-labeler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
           - name: worker-labels-conf
             mountPath: "/usr/src/app/worker-labels.conf"
             subPath: worker-labels.conf
           - name: spot-labels-conf
             mountPath: "/usr/src/app/spot-labels.conf"
             subPath: spot-labels.conf
      volumes:
       - name: worker-labels-conf
         configMap:
          name: worker-labels-conf
          items:
           - key: worker-labels.conf
             path: worker-labels.conf
       - name: spot-labels-conf
         configMap:
          name: spot-labels-conf
          items:
           - key: spot-labels.conf
             path: spot-labels.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
