---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    {{- include "node-labeler.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: dockerhub-regcred
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: AgDM9MjU3ukSdRAXv5yyqW15jOZ/xcXZWYOm2bcTl+EvBexqPsz3hdDQmM8SRBeNrXgzgXGddXt3ZyakTv7uV/mCnXizVP2Pg6pr0lAavg9xscD0Q/5P8Iu3xViz0zUNRXNTV87CAkD58Aa4KOPgIkRgKmTjMOdpN8r9AyEa506rnIk0Hl2zfClb3ds02D7ojc5I7v5CPyp6gEvpA3kZZAhl1CA1v6LYIAQqi3RHC+kWPpx7R+28QKddFxVroSZYC/VVZdHkrDxez/6GvsD8NZxvnLvndhiS8wAamlDC6BLgP+E48s+KoMqSORNIVCkSDQHze8011mcHNNMd8AuwI5TFMee6jsI7mvYiKxyGKs3Ko6/kGmGYdkuWfjsCbLy7dDyrukbpf2BWrNtFPdv0NjQ+wPnvDhKqyNcI1HLEyCUWbN4o8hH4P02PSMvlWPyPHsTcnEl/bdjTVuFEcMCQA7qVWEXmFT9J9k3sdmsQB24F33Fp35/DLBUFYgd1fIVvFJOn2Xcs692AomvivUrb0zapaldNJ6LyqZB04oZ7d6oldRN8YZlaWJmMdTr30xfxEllm0dqSMcz3WbbNWCIIEaGaWbUYo8hTLB7ujsPbNFbUwynEhw9UNeRRtqggPZvw0bGCAL1GAArNXxKv553Sr4qtKLypF7c5eBe5RNDbRG7UM0VVtJuQFCOOP9OcSaR3isp2GaLdLQLl3i8AHsq0I7pFV0ryGvfsWVihPz8UJiEJ2GEclfNIAaD09i00RX21BBoLu72U1dgnNh4mxwO4bXmYklPwl1xQIwFUWDiHtxHwMgQyfLNI6qBmb+PmPFrYN4vR3WfJiErg9cJRkW1WpxmlOiKi7mfxnaBORCSAJ0XixHiXFtTgyaQQ3gotDHg9v3JDJT2Dq6qru04AoxZq8kr52rK8YhMsGeYthdtK3QFvUO6eGUMvXznVJjagaDQFFxzSRUW+vCLE/VHn7mEn6K4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: dockerhub-regcred
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
