apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    {{- include "node-labeler.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: harbor-private
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: AgAhGdHidPQvGI2NEg/r//BGI8oqIKNHyT5D4ZJYbMT3A4vvoSwkY7GJlNMsGnsIZjLNtQditDUjRuUEdoLMg6GYzanfvEhTEr4lZHTVCu8phAU4wj1IPldCWcgrXOZrBEc3B2+PFuoimIrpzJCetSdsLOryL4BCKLJtNGo3Rxnm7WJAFsqAzPofytPljMg/1JDz+hHE4H8pkcS7M/p0K3CzqppdGnJasKCqHhik5iZFqyASG7iDxxyvXWNELb9ItQJsWOZdzPrDBnSNT82sKrLKqzYso4r6KGzZSk5nW4G2mA9/hnJGqPcQHiuh9rc2K/qXNPcPyBsOWVy5YJpGoVcW9Oo4ChYL9T7Nfw2tH0hnvM66wEfTTSwNx5L1vghHogr5WW9sLjRlJ0/zVO2I38eprvGHnzs54MjMTx+BI/0uUkHHKrk8nNqMPZEAvKBCDWB3EKFb7CB/b5TtgmT371Cl06GLibIkAQhQRYEjyQwnu6nZ45Dfp3HXqbs/rHmJftxVvoCgj03k/GBZewON23kKX5JCc7w+4v4ek2FHtjrmDSxcr5nswDSh+2syjUQb1UkBr0a1xUbdSPppVDSGCOig2I6Tjcsfqjcc35jZdhMsG0liIa6x5nxL1Z3R3R/Yl2N3oYyyviqDtzaNvA20znmwhBSpIcuuE4rXMS6tvxHEQ7gYp+CzVZ0lzK0WA2/sU6ElBBhD2bH7dXoIpp1n/RN05EBuGwqveju6I1bn1byGMes7SkAbQLWEE8iUfndKTGH7EPDhotx3zoHqwmD/rwHltN4fzKueOrO5IOj5VhVPI2vLSCVYF2MPZX06Y7es1ZjJUtiqRT/pm9Pn2MmrFBD1hHtfdzjGG9TPeAAS8SO1RH3GmQ4oHwHqWRwoac85wF8E9Q28Y3+O1NzfBlo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: harbor-private
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson