defaultNamespace: kube-system

helm:
  releaseName: node-labeler

targetCustomizations:
- name: k8s-us-central1
  helm:
    values:
      resource:
        limits:
          cpu: 50m
          memory: 80Mi
        requests:
          cpu: 20m
          memory: 50Mi
  clusterSelector:
    matchLabels:
      clusterName: k8s-us-central1
- name: k8s-us-east
  helm:
    values:
      replicaCount: 2
      resource:
        limits:
          cpu: 50m
          memory: 80Mi
        requests:
          cpu: 20m
          memory: 50Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
                  values:
                  - node-labeler
              topologyKey: kubernetes.io/hostname
  clusterSelector:
    matchLabels:
      clusterName: k8s-us-east
