---
name: Build container and push to GCR
on:
  push:
    tags:
    - '*'

env:
  GCP_PROJECT: kubernetes-346019
  REGISTRY: us.gcr.io
  IMAGE_NAME: private/node-labeler
  CONTEXT: docker
  CHART_PATH: helm/node-labeler

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version and build container
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: ${{ env.REGISTRY }}
          project_id: ${{ env.GCP_PROJECT }}
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
          dockerfile: ./${{ env.CONTEXT }}/Dockerfile
          context: ./${{ env.CONTEXT }}/
      - uses: actions/checkout@v2
      - name: Update image tag
        id: set_tag_name
        run: |
          sed -i "s|v[0-9].[0-9].[0-9].*|${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}|g" ./${{ env.CHART_PATH }}/values.yaml
          sed -i "s|v[0-9].[0-9].[0-9]|${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}|g" ./${{ env.CHART_PATH }}/Chart.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Actions
          commit_author: Author <github-actions@undependable.cloud>
          create_branch: true
          branch: 'feature/update-tag'
      - uses: ravsamhq/notify-slack-action@master
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: '[GitHub Actions] {workflow} has {status_message}'
          message_format: '{emoji} ${{ github.event.head_commit.author.name }} ${{ github.event.head_commit.message }}'
          footer: 'Repo: <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}